#!/usr/bin/env python3

import argparse
import json
import re
import time
import urllib.error
import urllib.parse
import urllib.request
from collections import defaultdict
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path


DATASET_URL = "https://publicreporting.cftc.gov/resource/72hh-3qpy.json"
LOOKBACK_WEEKS = 260
CONTRACTS = {
    "NG": "023651",
    "CL": "067651",
    "GC": "088691",
    "SI": "084691",
}
MONTHS = ("JAN", "FEB", "MAR", "APR", "MAY", "JUN",
          "JUL", "AUG", "SEP", "OCT", "NOV", "DEC")
BLOCK_PATTERN = re.compile(
    r"<!-- COT_DATA_START: generated by scripts/update_cot\.py -->.*?<!-- COT_DATA_END -->",
    re.DOTALL,
)
REPORT_DATE_PATTERN = re.compile(
    r'class="ms-cot-date" data-report-date="(\d{4}-\d{2}-\d{2})"'
)


def expected_report_date(today):
    latest_release_friday = today - timedelta(days=(today.weekday() - 4) % 7)
    return latest_release_friday - timedelta(days=3)


def embedded_report_date(html):
    match = REPORT_DATE_PATTERN.search(html)
    return date.fromisoformat(match.group(1)) if match else None


def fetch_rows(today):
    cutoff = today - timedelta(days=6 * 366)
    codes = ",".join(f"'{code}'" for code in CONTRACTS.values())
    params = {
        "$select": (
            "cftc_contract_market_code,report_date_as_yyyy_mm_dd,"
            "m_money_positions_long_all,m_money_positions_short_all"
        ),
        "$where": (
            f"cftc_contract_market_code in({codes}) AND "
            f"report_date_as_yyyy_mm_dd >= '{cutoff.isoformat()}T00:00:00.000'"
        ),
        "$order": "report_date_as_yyyy_mm_dd DESC",
        "$limit": "2000",
    }
    request = urllib.request.Request(
        f"{DATASET_URL}?{urllib.parse.urlencode(params)}",
        headers={"User-Agent": "InvestroLog-COT-Updater/1.0"},
    )
    for attempt in range(3):
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                return json.load(response)
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError):
            if attempt == 2:
                raise
            time.sleep(5 * (attempt + 1))


def percentile_rank(values):
    current = values[0]
    less = sum(value < current for value in values)
    equal = sum(value == current for value in values)
    rank = Decimal(100) * (Decimal(less) + Decimal(equal) / 2) / Decimal(len(values))
    return int(rank.quantize(Decimal("1"), rounding=ROUND_HALF_UP))


def calculate(rows, today):
    symbol_by_code = {code: symbol for symbol, code in CONTRACTS.items()}
    histories = defaultdict(list)
    seen = set()

    for row in rows:
        code = row.get("cftc_contract_market_code")
        if code not in symbol_by_code:
            continue
        report_date = date.fromisoformat(row["report_date_as_yyyy_mm_dd"][:10])
        key = (code, report_date)
        if key in seen:
            raise ValueError(f"Duplicate CFTC row for {code} on {report_date}")
        seen.add(key)
        net_position = (
            int(row["m_money_positions_long_all"])
            - int(row["m_money_positions_short_all"])
        )
        histories[symbol_by_code[code]].append((report_date, net_position))

    latest_dates = set()
    percentiles = {}
    for symbol in CONTRACTS:
        history = sorted(histories[symbol], reverse=True)[:LOOKBACK_WEEKS]
        if len(history) != LOOKBACK_WEEKS:
            raise ValueError(
                f"{symbol}: expected {LOOKBACK_WEEKS} reports, received {len(history)}"
            )
        latest_dates.add(history[0][0])
        percentiles[symbol] = percentile_rank([position for _, position in history])

    if len(latest_dates) != 1:
        raise ValueError(f"CFTC report dates differ by contract: {sorted(latest_dates)}")
    report_date = latest_dates.pop()
    expected = expected_report_date(today)
    if report_date != expected:
        raise ValueError(f"Expected CFTC report {expected}, received {report_date}")
    return report_date, percentiles


def render_block(report_date, percentiles):
    display_date = f"{report_date.day:02d} {MONTHS[report_date.month - 1]}"
    items = "\n".join(
        '<span class="ms-cot-item"><span class="ms-cot-sym">'
        f'{symbol}</span><span class="ms-cot-val" data-p="{percentiles[symbol]}">'
        f'p{percentiles[symbol]}</span></span>'
        for symbol in CONTRACTS
    )
    return f"""<!-- COT_DATA_START: generated by scripts/update_cot.py -->
<div class="ms-cot">
<div class="ms-cot-head">
<span>COT · MM percentile</span>
<span class="ms-cot-date" data-report-date="{report_date.isoformat()}">{display_date} · CFTC</span>
</div>
<div class="ms-cot-row">
{items}
</div>
</div>
<!-- COT_DATA_END -->"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--skip-if-current",
        action="store_true",
        help="Exit before the CFTC request when HTML already has the expected report.",
    )
    args = parser.parse_args()

    today = datetime.now(timezone.utc).date()
    index_path = Path(__file__).resolve().parents[1] / "index.html"
    html = index_path.read_text(encoding="utf-8")
    expected = expected_report_date(today)
    if args.skip_if_current and embedded_report_date(html) == expected:
        print(f"COT {expected.isoformat()} is already current; skipping CFTC request.")
        return

    report_date, percentiles = calculate(fetch_rows(today), today)
    updated, count = BLOCK_PATTERN.subn(render_block(report_date, percentiles), html)
    if count != 1:
        raise ValueError(f"Expected one generated COT block, found {count}")
    if updated != html:
        index_path.write_text(updated, encoding="utf-8")

    values = " · ".join(f"{symbol} p{value}" for symbol, value in percentiles.items())
    print(f"COT {report_date.isoformat()}: {values}")


if __name__ == "__main__":
    main()
